// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6RWN5yHvDCRJAl1RjgYUoZFGitJQsl00',
    appId: '1:466356818805:web:2312a124f4aefb8a01793c',
    messagingSenderId: '466356818805',
    projectId: 'kovilkanakku',
    authDomain: 'kovilkanakku.firebaseapp.com',
    storageBucket: 'kovilkanakku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh3fnkBb9jsnho-LyB8C_CN2PjUTfTrIE',
    appId: '1:466356818805:android:87463338713f667801793c',
    messagingSenderId: '466356818805',
    projectId: 'kovilkanakku',
    storageBucket: 'kovilkanakku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdL-enU5F3JCY-IadonW2rB4f9NAh6S7E',
    appId: '1:466356818805:ios:b58ccaa2b66c275f01793c',
    messagingSenderId: '466356818805',
    projectId: 'kovilkanakku',
    storageBucket: 'kovilkanakku.firebasestorage.app',
    iosBundleId: 'com.balamurugan.temple',
  );
}
